from pathlib import Path

from openpyxl import load_workbook
from collections import Counter


class ResearchSynthesisEngine:
    """
    AROS Research Synthesis Engine v1.

    Converts Intelligent Literature Matrix
    into researcher-level synthesis.

    Domain neutral.
    """


    def synthesize(
        self,
        output_type,
        project_id
    ):

        base = (
            Path("Research_Output")
            / output_type
            / "Researched_Library"
            / project_id
        )


        matrix = (
            base
            / "05_Intelligent_Matrix"
            / "Intelligent_Literature_Matrix.xlsx"
        )


        output = (
            base
            / "06_Research_Synthesis"
        )


        output.mkdir(
            parents=True,
            exist_ok=True
        )


        wb = load_workbook(matrix)

        ws = wb.active


        headers = [
            cell.value
            for cell in ws[1]
        ]


        rows = []

        for row in ws.iter_rows(
            min_row=2,
            values_only=True
        ):

            rows.append(
                dict(
                    zip(headers,row)
                )
            )


        theories = Counter()

        methods = Counter()

        variables = Counter()


        for r in rows:

            for item in str(
                r.get("Theory")
            ).split(","):

                if item.strip():
                    theories[item.strip()] += 1


            for item in str(
                r.get("Methodology")
            ).split(","):

                if item.strip():
                    methods[item.strip()] += 1


            for item in str(
                r.get("Variables")
            ).split(","):

                if item.strip():
                    variables[item.strip()] += 1



        report = f"""
# AROS Research Synthesis Report


## Literature Coverage

Total Papers Analysed:

{len(rows)}



## Dominant Theories

{dict(theories.most_common())}



## Dominant Methodologies

{dict(methods.most_common())}



## Dominant Variables / Constructs

{dict(variables.most_common())}



## Research Gap Signals

- Check underexplored theories
- Check limited methodologies
- Identify missing variable combinations
- Explore interdisciplinary extensions


Generated by AROS Research Intelligence Engine.
"""


        file = (
            output
            / "research_synthesis_report.md"
        )


        file.write_text(
            report,
            encoding="utf-8"
        )


        return str(file)
